metadata:
  years: &years [1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

granted:    
  minimal: &minimal-granted
    database: https://s3.amazonaws.com/data.patentsview.org/download
    loader: "{database}/{table}.tsv.zip"
    tables:
      - g_patent
      - g_location_not_disambiguated
      - g_assignee_not_disambiguated
      - g_inventor_not_disambiguated
  downloads: 
    <<: *minimal-granted  # Extends the minimal tables.
    tables:
      - g_patent
      - g_location_not_disambiguated
      - g_assignee_not_disambiguated
      - g_inventor_not_disambiguated
      - g_applicant_not_disambiguated
      - g_application
      - g_assignee_disambiguated
      - g_attorney_disambiguated
      - g_attorney_not_disambiguated
      - g_botanic
      - g_cpc_at_issue
      - g_cpc_current
      - g_cpc_title
      - g_examiner_not_disambiguated
      - g_figures
      - g_foreign_citation
      - g_foreign_priority
      - g_gov_interest
      - g_gov_interest_contracts
      - g_gov_interest_org
      - g_inventor_disambiguated
      - g_ipc_at_issue
      - g_location_disambiguated
      - g_other_reference
      - g_patent_abstract
      - g_pct_data
      - g_persistent_assignee
      - g_persistent_inventor
      - g_rel_app_text
      - g_us_application_citation
      - g_us_patent_citation
      - g_us_rel_doc
      - g_us_term_of_grant
      - g_uspc_at_issue
      - g_wipo_technology
    brief_summary: 
      database: "https://s3.amazonaws.com/data.patentsview.org/brief-summary-text"
      loader: "{database}/g_brf_sum_text_{table}.tsv.zip"
      tables: *years
    claims: 
      database: "https://s3.amazonaws.com/data.patentsview.org/claims"
      loader: "{database}/g_claims_{table}.tsv.zip"
      tables: *years
    detail_description: 
      database: "https://s3.amazonaws.com/data.patentsview.org/detail-description-text"
      loader: "{database}/g_detail_desc_text_{table}.tsv.zip"
      tables: *years
    drawing_description:
      database: "https://s3.amazonaws.com/data.patentsview.org/draw-description-text"
      loader: "{database}/g_draw_desc_text_{table}.tsv.zip"
      tables: *years

pre-grant:
  description: https://patentsview.org/download/pg-data-download-dictionary
  database: https://s3.amazonaws.com/data.patentsview.org/pregrant_publications
  loader: "{database}/{table_name}.tsv.zip"
  tables:
    minimal: &minimal-pregrant-table
      - pg_published_application
      - pg_applicant_not_disambiguated
      - pg_assignee_not_disambiguated
      - pg_inventor_not_disambiguated
    core:
      <<: *minimal-pregrant-table
      - pg_assignee_disambiguated
      - pg_cpc_at_issue
      - pg_cpc_current
      - pg_cpc_title
      - pg_foreign_priority
      - pg_gov_interest
      - pg_gov_interest_contracts
      - pg_gov_interest_org
      - pg_granted_pgpubs_crosswalk
      - pg_inventor_disambiguated
      - pg_ipc_at_issue
      - pg_location_disambiguated
      - pg_location_not_disambiguated
      - pg_pct_data
      - pg_persistent_assignee
      - pg_persistent_inventor
      - pg_published_application_abstract
      - pg_rel_app_text
      - pg_us_rel_doc
      - pg_uspc_at_issue
      - pg_wipo_technology