name: pv-code-examples

channels: 
  - conda-forge

dependencies:
  # R dependencies
  - r-base=4.4
  - r-tidyverse=2.0.0
  - r-vroom=1.6

  # Python dependencies
  - python=3.13
  - pip
  - pip:
    - jupyter
    - ipykernel
    - pandas
    - duckdb