granted:
  description: https://patentsview.org/download/data-download-dictionary
  database: https://s3.amazonaws.com/data.patentsview.org/download
  loader: "{database}/{table_name}.tsv.zip"
  tables:
    - g_applicant_not_disambiguated
    - g_application
    - g_assignee_disambiguated
    - g_assignee_not_disambiguated
    - g_attorney_disambiguated
    - g_attorney_not_disambiguated
    - g_botanic
    - g_cpc_at_issue
    - g_cpc_current
    - g_cpc_title
    - g_examiner_not_disambiguated
    - g_figures
    - g_foreign_citation
    - g_foreign_priority
    - g_gov_interest
    - g_gov_interest_contracts
    - g_gov_interest_org
    - g_inventor_disambiguated
    - g_inventor_not_disambiguated
    - g_ipc_at_issue
    - g_location_disambiguated
    - g_location_not_disambiguated 
    - g_other_reference
    - g_patent
    - g_patent_abstract
    - g_pct_data
    - g_persistent_assignee
    - g_persistent_inventor
    - g_rel_app_text
    - g_us_application_citation
    - g_us_patent_citation
    - g_us_rel_doc
    - g_us_term_of_grant
    - g_uspc_at_issue
    - g_wipo_technology

pre-grant:
  description: https://patentsview.org/download/pg-data-download-dictionary
  database: https://s3.amazonaws.com/data.patentsview.org/pregrant_publications
  loader: "{database}/{table_name}.tsv.zip"
  tables:
    - pg_applicant_not_disambiguated
    - pg_assignee_disambiguated
    - pg_assignee_not_disambiguated
    - pg_cpc_at_issue
    - pg_cpc_current
    - pg_cpc_title
    - pg_foreign_priority
    - pg_gov_interest
    - pg_gov_interest_contracts
    - pg_gov_interest_org
    - pg_granted_pgpubs_crosswalk
    - pg_inventor_disambiguated
    - pg_inventor_not_disambiguated
    - pg_ipc_at_issue
    - pg_location_disambiguated
    - pg_location_not_disambiguated
    - pg_pct_data
    - pg_persistent_assignee
    - pg_persistent_inventor
    - pg_rel_app_text
    - pg_us_rel_doc
    - pg_uspc_at_issue
    - pg_wipo_technology
