name: Pytest

on:
  push:
  pull_request:

jobs:
  test-pandas-read-in:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
      - run: conda activate pv-code-examples && pytest