name: Test Bulk Download Read-In

on:
  push:
  pull_request:

jobs:
  test-pandas-read-in:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          pip install pyyaml
          python 03_bulk_download_read_in/tests/test_source_urls.py 
